# Generated by Django 5.1.2 on 2024-11-02 18:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ask', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='answerlike',
            name='profile',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ask.profile', verbose_name='Профиль'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='answerlike',
            name='question',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ask.answer', verbose_name='Ответ'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='answerlike',
            name='status',
            field=models.IntegerField(choices=[(1, 'Нравится'), (0, 'Не нравится')], default=1, verbose_name='Статус'),
            preserve_default=False,
        ),
    ]
