# Generated by Django 5.1.2 on 2024-11-02 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ask', '0002_answerlike_profile_answerlike_question_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answerlike',
            old_name='question',
            new_name='answer',
        ),
    ]
