# Generated by Django 5.1.2 on 2024-11-02 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ask', '0004_alter_answer_question_alter_question_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answerlike',
            name='status',
            field=models.IntegerField(choices=[(1, 'Нравится'), (-1, 'Не нравится')], verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='questionlike',
            name='status',
            field=models.IntegerField(choices=[(1, 'Нравится'), (-1, 'Не нравится')], verbose_name='Статус'),
        ),
    ]
