# Generated by Django 5.1.2 on 2024-11-16 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ask', '0005_alter_answerlike_status_alter_questionlike_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='nickname',
            field=models.TextField(default='user', verbose_name='Отображаемое имя'),
            preserve_default=False,
        ),
    ]
