# Generated by Django 5.1.2 on 2024-12-21 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ask', '0006_profile_nickname'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='answerlike',
            unique_together={('answer', 'profile')},
        ),
        migrations.AlterUniqueTogether(
            name='questionlike',
            unique_together={('question', 'profile')},
        ),
    ]
