# Generated by Django 5.1.2 on 2024-12-21 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ask', '0008_remove_profile_rating_alter_profile_nickname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='correct',
            field=models.BooleanField(default=False, verbose_name='Правильный ответ'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='rating',
            field=models.IntegerField(default=0, verbose_name='Рейтинг'),
        ),
    ]
