# Generated by Django 5.1.2 on 2024-12-22 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ask', '0010_alter_question_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answerlike',
            name='status',
            field=models.IntegerField(choices=[(1, 'Нравится'), (-1, 'Не нравится')], default=1, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='questionlike',
            name='status',
            field=models.IntegerField(choices=[(1, 'Нравится'), (-1, 'Не нравится')], default=1, verbose_name='Статус'),
        ),
    ]
