# Generated by Django 5.1.2 on 2024-12-22 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ask', '0011_alter_answerlike_status_alter_questionlike_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='rating',
        ),
        migrations.RemoveField(
            model_name='question',
            name='rating',
        ),
    ]
